import type { ActionDef, SubField } from '../../../types/model'
import {
  ABC_REMINDER,
  BATT_REMINDER,
  FAST_REMINDER,
  GRADE_REMINDER,
  STABILITE_REMINDER,
  TRANSFUSION_REMINDER,
  TRAUMA_CENTER_REMINDER,
  TXA_REMINDER,
  VITTEL_INPUT_IDS,
  VITTEL_REMINDER,
  VITTEL_SUBFIELDS,
} from './clinical'
import {
  BURN_FLUID_REMINDER,
  WALLACE_ACTION_ID,
  WALLACE_INPUT_IDS,
  WALLACE_REMINDER,
  WALLACE_SUBFIELDS,
  WALLACE_WEIGHTS,
} from './burns'

/** Sous-menu commun aux boutons ACR (régulation et pré-hospitalier). */
const ACR_SUBFIELDS: SubField[] = [
  { id: 'noflow', type: 'number', label: 'No-flow', unit: 'min' },
  { id: 'lowflow', type: 'number', label: 'Low-flow', unit: 'min' },
  { id: 'adrenaline', type: 'number', label: 'Adrénaline', unit: 'mg' },
  { id: 'cee', type: 'number', label: 'CEE (nombre de chocs)' },
  { id: 'cordarone', type: 'number', label: 'Cordarone / amiodarone', unit: 'mg' },
  { id: 'racs', type: 'timestamp', label: 'RACS (reprise d’activité cardiaque spontanée)' },
]

/**
 * Toutes les actions de la filière polytraumatisé, réparties sur les 3 pistes.
 * `defaultTimeOffsetMin` = position indicative sur la timeline tant que l'action
 * n'est pas réalisée (elle se fige à son horodatage réel une fois cochée/remplie).
 * `category` = icône (timeline réduite + glyphe des pastilles).
 */
export const actions: ActionDef[] = [
  /* ----------------------------- RÉGULATION ----------------------------- */
  {
    id: 'regul.appel.vittel',
    trackId: 'regul',
    sectionId: 'regul.appel',
    label: 'Critères de Vittel',
    type: 'computed',
    category: 'score',
    computed: { method: 'count', inputs: VITTEL_INPUT_IDS },
    defaultTimeOffsetMin: 0,
    detail: { reminder: VITTEL_REMINDER, subFields: VITTEL_SUBFIELDS },
  },
  {
    id: 'regul.moyens.vsav',
    trackId: 'regul',
    sectionId: 'regul.moyens',
    label: 'VSAV engagé',
    type: 'checkbox',
    category: 'means',
    defaultTimeOffsetMin: 2,
  },
  {
    id: 'regul.moyens.smur',
    trackId: 'regul',
    sectionId: 'regul.moyens',
    label: 'SMUR engagé',
    type: 'checkbox',
    category: 'means',
    defaultTimeOffsetMin: 2,
  },
  {
    id: 'regul.moyens.heli',
    trackId: 'regul',
    sectionId: 'regul.moyens',
    label: 'HéliSMUR',
    type: 'checkbox',
    category: 'means',
    defaultTimeOffsetMin: 3,
  },
  {
    id: 'regul.tc.niveau1',
    trackId: 'regul',
    sectionId: 'regul.orientation',
    label: 'Niveau I — CHU de référence',
    type: 'checkbox',
    category: 'destination',
    defaultTimeOffsetMin: 9,
    detail: { reminder: TRAUMA_CENTER_REMINDER },
  },
  {
    id: 'regul.tc.niveau2',
    trackId: 'regul',
    sectionId: 'regul.orientation',
    label: 'Niveau II',
    type: 'checkbox',
    category: 'destination',
    defaultTimeOffsetMin: 9,
    detail: { reminder: TRAUMA_CENTER_REMINDER },
  },
  {
    id: 'regul.tc.niveau3',
    trackId: 'regul',
    sectionId: 'regul.orientation',
    label: 'Niveau III — proximité',
    type: 'checkbox',
    category: 'destination',
    defaultTimeOffsetMin: 9,
    detail: { reminder: TRAUMA_CENTER_REMINDER },
  },
  {
    id: 'regul.tc.ctb',
    trackId: 'regul',
    sectionId: 'regul.orientation',
    label: 'CTB — centre des brûlés',
    type: 'checkbox',
    category: 'burns',
    defaultTimeOffsetMin: 9,
    detail: {
      reminder:
        'Centre de traitement des brûlés : orienter si brûlure étendue/profonde, inhalation de fumées, brûlure du visage/voies aériennes, ou terrain à risque. À articuler avec le trauma center si polytraumatisme associé.',
    },
  },
  {
    id: 'regul.tc.pediatrie',
    trackId: 'regul',
    sectionId: 'regul.orientation',
    label: 'Centre pédiatrique',
    type: 'checkbox',
    category: 'pediatrics',
    defaultTimeOffsetMin: 9,
    detail: {
      reminder:
        'Orientation vers un centre disposant d’un accueil pédiatrique des traumatisés (réanimation et chirurgie pédiatriques). À privilégier selon l’âge et le plateau technique régional.',
    },
  },
  {
    id: 'regul.orientation.destination',
    trackId: 'regul',
    sectionId: 'regul.orientation',
    label: 'Destination retenue',
    type: 'select',
    category: 'destination',
    options: [
      { value: 'niveau1', label: 'Niveau I — CHU' },
      { value: 'niveau2', label: 'Niveau II' },
      { value: 'niveau3', label: 'Niveau III — proximité' },
      { value: 'ctb', label: 'CTB — brûlés' },
      { value: 'pediatrie', label: 'Centre pédiatrique' },
      { value: 'autre', label: 'Autre' },
    ],
    defaultTimeOffsetMin: 11,
  },
  {
    id: 'regul.prealerte.centre',
    trackId: 'regul',
    sectionId: 'regul.prealerte',
    label: 'Pré-alerte du centre receveur',
    type: 'checkbox',
    category: 'transmission',
    lockedByDefault: true,
    defaultTimeOffsetMin: 12,
  },
  {
    id: 'regul.prealerte.rea',
    trackId: 'regul',
    sectionId: 'regul.prealerte',
    label: 'Recherche place de réanimation',
    type: 'checkbox',
    category: 'activation',
    defaultTimeOffsetMin: 13,
  },
  {
    id: 'regul.bloc.anticip',
    trackId: 'regul',
    sectionId: 'regul.bloc',
    label: 'Anticiper bloc / artério / PSL',
    type: 'checkbox',
    category: 'surgery',
    defaultTimeOffsetMin: 12,
  },

  /* --------------------------- PRÉ-HOSPITALIER --------------------------- */
  {
    id: 'prehosp.x.hemostase',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'X — Hémorragie exsanguinante (garrot / packing / CCP)',
    type: 'checkbox',
    category: 'hemorrhage',
    defaultTimeOffsetMin: 2,
    detail: {
      reminder:
        'X (eXsanguination) en tête du XABCDE : contrôle immédiat d’une hémorragie cataclysmique avant la suite du bilan — garrot tourniquet, pansement/packing hémostatique, compression, ceinture pelvienne.',
    },
  },
  {
    id: 'prehosp.a.lvas',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'A — LVAS / minerve cervicale',
    type: 'checkbox',
    category: 'airway',
    defaultTimeOffsetMin: 3,
  },
  {
    id: 'prehosp.b.spo2',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'B — SpO₂',
    type: 'number',
    category: 'breathing',
    unit: '%',
    placeholder: 'ex. 94',
    defaultTimeOffsetMin: 4,
  },
  {
    id: 'prehosp.c.pas',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'C — PAS',
    type: 'number',
    category: 'circulation',
    unit: 'mmHg',
    placeholder: 'ex. 85',
    defaultTimeOffsetMin: 4,
  },
  {
    id: 'prehosp.c.fc',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'C — FC',
    type: 'number',
    category: 'circulation',
    unit: '/min',
    placeholder: 'ex. 124',
    defaultTimeOffsetMin: 4,
  },
  {
    id: 'prehosp.d.gcs',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'D — Glasgow (GCS)',
    type: 'number',
    category: 'neuro',
    placeholder: '3–15',
    defaultTimeOffsetMin: 5,
  },
  {
    id: 'prehosp.d.anisocorie',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'D — Anisocorie',
    type: 'checkbox',
    category: 'neuro',
    defaultTimeOffsetMin: 5,
  },
  {
    id: 'prehosp.e.hypothermie',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'E — Prévention hypothermie',
    type: 'checkbox',
    category: 'exposure',
    defaultTimeOffsetMin: 6,
  },
  {
    id: 'prehosp.e.temperature',
    trackId: 'prehosp',
    sectionId: 'prehosp.abcde',
    label: 'E — Température',
    type: 'number',
    category: 'exposure',
    unit: '°C',
    placeholder: 'ex. 36,5',
    defaultTimeOffsetMin: 6,
  },
  {
    id: 'prehosp.g.garrot',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Contrôle hémorragie (garrot)',
    type: 'checkbox',
    category: 'hemorrhage',
    defaultTimeOffsetMin: 5,
  },
  {
    id: 'prehosp.g.vvp',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: '2 VVP / intra-osseux',
    type: 'checkbox',
    category: 'circulation',
    defaultTimeOffsetMin: 5,
  },
  {
    id: 'prehosp.g.isr',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Intubation (ISR si GCS ≤ 8)',
    type: 'checkbox',
    category: 'airway',
    defaultTimeOffsetMin: 6,
  },
  {
    id: 'prehosp.g.exsufflation',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Exsufflation / drainage thoracique',
    type: 'checkbox',
    category: 'breathing',
    defaultTimeOffsetMin: 6,
  },
  {
    id: 'prehosp.g.pelvien',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Ceinture pelvienne',
    type: 'checkbox',
    category: 'gesture',
    defaultTimeOffsetMin: 6,
  },
  {
    id: 'prehosp.acsos',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'ACSOS',
    type: 'checkbox',
    category: 'neuro',
    defaultTimeOffsetMin: 6,
    detail: {
      recapSubFields: true,
      reminder:
        'ACSOS — agressions cérébrales secondaires d’origine systémique. Les prévenir / corriger : hypotension, hypoxémie, hypo/hypercapnie, anémie, hyperthermie, hyperglycémie, hyponatrémie. Objectifs préhospitaliers : PAS ≥ 90 mmHg (PAM ≥ 55 si hémorragie), SpO₂ ≥ 90 %, normocapnie.',
      subFields: [
        {
          id: 'pam-tc',
          type: 'number',
          label: 'PA moyenne — objectif TC (≥ 90 mmHg)',
          unit: 'mmHg',
          group: 'Tension artérielle',
          gauge: { min: 30, max: 150, redBelow: 90 },
        },
        {
          id: 'pam-hemo',
          type: 'number',
          label: 'PA moyenne — objectif hémorragie (≥ 55 mmHg)',
          unit: 'mmHg',
          group: 'Tension artérielle',
          gauge: { min: 30, max: 150, redBelow: 55 },
        },
        {
          id: 'capnie',
          type: 'number',
          label: 'Capnie (EtCO₂)',
          unit: 'mmHg',
          group: 'Ventilation / oxygénation',
          gauge: { min: 15, max: 60, normalMin: 35, normalMax: 40 },
        },
        {
          id: 'spo2',
          type: 'number',
          label: 'SpO₂ (hypoxémie si < 90 %)',
          unit: '%',
          group: 'Ventilation / oxygénation',
          bindTo: 'prehosp.b.spo2',
          gauge: { min: 70, max: 100, redBelow: 90 },
        },
        {
          id: 'hcue',
          type: 'text',
          label: 'Anémie aiguë — Hcue =',
          placeholder: 'ex. 9 g/dL',
          group: 'Autres ACSOS',
        },
        {
          id: 'temperature',
          type: 'number',
          label: 'Température',
          unit: '°C',
          group: 'Autres ACSOS',
          bindTo: 'prehosp.e.temperature',
          gauge: { min: 33, max: 42, step: 0.1, normalMin: 36, normalMax: 37.9 },
        },
        { id: 'hyperglycemie', type: 'checkbox', label: 'Hyperglycémie', group: 'Autres ACSOS' },
        { id: 'hyponatremie', type: 'checkbox', label: 'Hyponatrémie', group: 'Autres ACSOS' },
      ],
    },
  },
  {
    id: 'prehosp.acr',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'ACR',
    type: 'checkbox',
    category: 'circulation',
    defaultTimeOffsetMin: 0,
    detail: {
      recapSubFields: true,
      reminder:
        'Arrêt cardio-respiratoire — RCP selon recommandations. Consigner no-flow / low-flow, adrénaline, chocs externes (CEE), amiodarone (Cordarone).',
      subFields: ACR_SUBFIELDS,
    },
  },
  {
    id: 'regul.acr',
    trackId: 'regul',
    sectionId: 'regul.appel',
    label: 'ACR',
    type: 'checkbox',
    category: 'circulation',
    defaultTimeOffsetMin: 0,
    detail: {
      recapSubFields: true,
      reminder:
        'Arrêt cardio-respiratoire signalé à l’appel — guidage RCP. Consigner no-flow / low-flow, adrénaline, chocs externes (CEE), amiodarone (Cordarone).',
      subFields: ACR_SUBFIELDS,
    },
  },
  {
    id: 'prehosp.transport.evolution',
    trackId: 'prehosp',
    sectionId: 'prehosp.transport',
    label: 'Évolution',
    type: 'text',
    category: 'transmission',
    defaultTimeOffsetMin: 14,
    detail: {
      recapSubFields: false,
      widget: 'evolutionLog',
      reminder:
        'Journal d’évolution pendant le transport : chaque note est horodatée à l’instant où vous l’ajoutez, et reprise dans la synthèse chronologique.',
    },
  },
  {
    id: 'prehosp.g.expansion',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Expansion volémique',
    type: 'checkbox',
    category: 'circulation',
    defaultTimeOffsetMin: 6,
  },
  {
    id: 'prehosp.g.antibioprophylaxie',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Antibioprophylaxie',
    type: 'checkbox',
    category: 'medication',
    defaultTimeOffsetMin: 8,
  },
  {
    id: 'prehosp.g.octaplas',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'OctaplasLG (plasma SD)',
    type: 'checkbox',
    category: 'transfusion',
    defaultTimeOffsetMin: 7,
    detail: {
      reminder:
        'OctaplasLG — plasma humain viro-atténué par solvant-détergent (SD), prêt à l’emploi, groupe-compatible. Réanimation hémostatique du choc hémorragique (ratio ≈ 1:1:1). Mis en avant dès le préhospitalier sur BATT ≥ 8. Posologie et place selon le protocole local.',
    },
  },
  {
    id: 'prehosp.g.osmotherapie',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Osmothérapie',
    type: 'checkbox',
    category: 'medication',
    defaultTimeOffsetMin: 7,
    detail: {
      reminder:
        'Osmothérapie (HTIC / signes d’engagement) — au choix selon le protocole local.',
      subFields: [
        { id: 'mannitol', type: 'checkbox', label: 'Mannitol 20 % — 0,5–1 g/kg en 15–20 min' },
        { id: 'ssh', type: 'checkbox', label: 'SSH (NaCl 20 %) — 12 g IVSE sur 20 min' },
      ],
    },
  },
  {
    id: 'prehosp.g.txa',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Acide tranexamique (TXA)',
    type: 'checkbox',
    category: 'medication',
    defaultTimeOffsetMin: 7,
    detail: { reminder: TXA_REMINDER },
  },
  {
    id: 'prehosp.g.nad',
    trackId: 'prehosp',
    sectionId: 'prehosp.gestes',
    label: 'Noradrénaline',
    type: 'checkbox',
    category: 'medication',
    defaultTimeOffsetMin: 7,
  },

  /* ------------------------------- BRÛLURES ------------------------------- */
  {
    id: WALLACE_ACTION_ID,
    trackId: 'prehosp',
    sectionId: 'prehosp.brulures',
    label: 'SCB — règle de Wallace',
    type: 'computed',
    category: 'burns',
    unit: '%',
    computed: { method: 'sum', inputs: WALLACE_INPUT_IDS, weights: WALLACE_WEIGHTS },
    defaultTimeOffsetMin: 6,
    detail: { reminder: WALLACE_REMINDER, subFields: WALLACE_SUBFIELDS, widget: 'burnBodyMap' },
  },
  {
    id: 'prehosp.brulures.remplissage',
    trackId: 'prehosp',
    sectionId: 'prehosp.brulures',
    label: 'Remplissage 20 ml/kg (1ʳᵉ heure)',
    type: 'checkbox',
    category: 'circulation',
    lockedByDefault: true,
    defaultTimeOffsetMin: 8,
    detail: { reminder: BURN_FLUID_REMINDER },
  },

  /* --- Score ABC : items en sous-menu (seul l'encart du score s'affiche sur la piste) --- */
  {
    id: 'prehosp.scores.shockindex',
    trackId: 'prehosp',
    sectionId: 'prehosp.scores',
    label: 'Shock Index (FC / PAS)',
    type: 'computed',
    category: 'score',
    computed: { method: 'ratio', inputs: ['prehosp.c.fc', 'prehosp.c.pas'] },
    defaultTimeOffsetMin: 6,
    detail: {
      reminder:
        'Shock Index = FC / PAS. Normal ≈ 0,5–0,7 ; ≥ 0,9–1,0 évoque un choc hémorragique / une hypovolémie significative.',
    },
  },
  {
    id: 'prehosp.scores.abc',
    trackId: 'prehosp',
    sectionId: 'prehosp.scores',
    label: 'Score ABC (transfusion)',
    type: 'computed',
    category: 'score',
    computed: {
      method: 'count',
      inputs: [
        'prehosp.scores.abc::penetrant',
        'prehosp.scores.abc::fast',
        'prehosp.scores.abc::pas90',
        'prehosp.scores.abc::fc120',
      ],
    },
    defaultTimeOffsetMin: 8,
    detail: {
      reminder: ABC_REMINDER,
      subFields: [
        { id: 'penetrant', type: 'checkbox', label: 'Mécanisme pénétrant' },
        { id: 'fast', type: 'checkbox', label: 'FAST positif (e-FAST)' },
        { id: 'pas90', type: 'checkbox', label: 'PAS ≤ 90 mmHg' },
        { id: 'fc120', type: 'checkbox', label: 'FC ≥ 120 /min' },
      ],
    },
  },

  /* --- Score BATT : items pondérés en sous-menu (seul l'encart du score s'affiche) --- */
  {
    id: 'prehosp.scores.batt',
    trackId: 'prehosp',
    sectionId: 'prehosp.scores',
    label: 'Score BATT (risque hémorragique)',
    type: 'computed',
    category: 'score',
    computed: {
      method: 'sum',
      inputs: [
        'prehosp.scores.batt::age65',
        'prehosp.scores.batt::age75',
        'prehosp.scores.batt::pas60',
        'prehosp.scores.batt::pas100',
        'prehosp.scores.batt::gcs8',
        'prehosp.scores.batt::gcs12',
        'prehosp.scores.batt::resp',
        'prehosp.scores.batt::fc100',
        'prehosp.scores.batt::penetrant',
        'prehosp.scores.batt::cinetique',
      ],
      weights: {
        'prehosp.scores.batt::age65': 1,
        'prehosp.scores.batt::age75': 2,
        'prehosp.scores.batt::pas60': 14,
        'prehosp.scores.batt::pas100': 5,
        'prehosp.scores.batt::gcs8': 4,
        'prehosp.scores.batt::gcs12': 3,
        'prehosp.scores.batt::resp': 2,
        'prehosp.scores.batt::fc100': 1,
        'prehosp.scores.batt::penetrant': 2,
        'prehosp.scores.batt::cinetique': 2,
      },
    },
    defaultTimeOffsetMin: 9,
    detail: {
      reminder: BATT_REMINDER,
      subFields: [
        { id: 'age65', type: 'checkbox', label: 'Âge 65–74 ans (+1)', group: 'Âge (un seul palier)' },
        { id: 'age75', type: 'checkbox', label: 'Âge ≥ 75 ans (+2)', group: 'Âge (un seul palier)' },
        { id: 'pas60', type: 'checkbox', label: 'PAS < 60 mmHg (+14)', group: 'Pression artérielle (un seul palier)' },
        { id: 'pas100', type: 'checkbox', label: 'PAS 60–99 mmHg (+5)', group: 'Pression artérielle (un seul palier)' },
        { id: 'gcs8', type: 'checkbox', label: 'Glasgow ≤ 8 (+4)', group: 'Glasgow (un seul palier)' },
        { id: 'gcs12', type: 'checkbox', label: 'Glasgow 9–12 (+3)', group: 'Glasgow (un seul palier)' },
        { id: 'resp', type: 'checkbox', label: 'FR < 10 ou ≥ 30 /min, ou SpO₂ < 90 % (+2)', group: 'Autres' },
        { id: 'fc100', type: 'checkbox', label: 'FC > 100 /min (+1)', group: 'Autres' },
        { id: 'penetrant', type: 'checkbox', label: 'Traumatisme pénétrant (+2)', group: 'Autres' },
        { id: 'cinetique', type: 'checkbox', label: 'Traumatisme à haute cinétique (+2)', group: 'Autres' },
      ],
    },
  },
  {
    id: 'prehosp.scores.hemodynamique',
    trackId: 'prehosp',
    sectionId: 'prehosp.scores',
    label: 'État hémodynamique',
    type: 'select',
    category: 'vitals',
    options: [
      { value: 'stable', label: 'Stable' },
      { value: 'instable', label: 'Instable' },
    ],
    defaultTimeOffsetMin: 7,
  },
  {
    id: 'prehosp.scores.grade',
    trackId: 'prehosp',
    sectionId: 'prehosp.scores',
    label: 'Grade de gravité',
    type: 'select',
    category: 'score',
    options: [
      { value: 'A', label: 'Grade A' },
      { value: 'B', label: 'Grade B' },
      { value: 'C', label: 'Grade C' },
    ],
    defaultTimeOffsetMin: 8,
    detail: { reminder: GRADE_REMINDER },
  },
  {
    id: 'prehosp.transmission.bilan',
    trackId: 'prehosp',
    sectionId: 'prehosp.transmission',
    label: 'Bilan transmis à la régulation',
    type: 'checkbox',
    category: 'transmission',
    defaultTimeOffsetMin: 9,
  },

  /* -------------------------- INTRA-HOSPITALIER -------------------------- */
  {
    id: 'intra.activation.equipe',
    trackId: 'intra',
    sectionId: 'intra.activation',
    label: 'Activation équipe trauma',
    type: 'checkbox',
    category: 'activation',
    lockedByDefault: true,
    defaultTimeOffsetMin: 12,
  },
  {
    id: 'intra.imagerie.efast',
    trackId: 'intra',
    sectionId: 'intra.imagerie',
    label: 'e-FAST au déchocage',
    type: 'checkbox',
    category: 'imaging',
    defaultTimeOffsetMin: 14,
    detail: { reminder: FAST_REMINDER },
  },
  {
    id: 'intra.imagerie.rt',
    trackId: 'intra',
    sectionId: 'intra.imagerie',
    label: 'Radio thorax',
    type: 'checkbox',
    category: 'imaging',
    defaultTimeOffsetMin: 14,
  },
  {
    id: 'intra.imagerie.bassin',
    trackId: 'intra',
    sectionId: 'intra.imagerie',
    label: 'Radio bassin',
    type: 'checkbox',
    category: 'imaging',
    defaultTimeOffsetMin: 14,
  },
  {
    id: 'intra.imagerie.bio',
    trackId: 'intra',
    sectionId: 'intra.imagerie',
    label: 'Bilan bio (groupe-RAI, hémostase, lactate)',
    type: 'checkbox',
    category: 'score',
    defaultTimeOffsetMin: 14,
  },
  {
    id: 'intra.imagerie.bodyct',
    trackId: 'intra',
    sectionId: 'intra.imagerie',
    label: 'Body-CT (si stabilisé)',
    type: 'checkbox',
    category: 'imaging',
    defaultTimeOffsetMin: 16,
    detail: { reminder: STABILITE_REMINDER },
  },
  {
    id: 'intra.transfusion.ptm',
    trackId: 'intra',
    sectionId: 'intra.transfusion',
    label: 'Protocole transfusion massive (1:1:1)',
    type: 'checkbox',
    category: 'transfusion',
    defaultTimeOffsetMin: 16,
    detail: { reminder: TRANSFUSION_REMINDER },
  },
  {
    id: 'intra.transfusion.octaplas',
    trackId: 'intra',
    sectionId: 'intra.transfusion',
    label: 'OctaplasLG (plasma SD)',
    type: 'checkbox',
    category: 'transfusion',
    defaultTimeOffsetMin: 16,
    detail: {
      reminder:
        'OctaplasLG — plasma humain viro-atténué par solvant-détergent (SD), prêt à l’emploi, groupe-compatible. Alternative/complément aux PFC dans la réanimation hémostatique du choc hémorragique (ratio ≈ 1:1:1). Déclenché ici sur BATT ≥ 8. Posologie et place selon le protocole local.',
    },
  },
  {
    id: 'intra.bloc.damagecontrol',
    trackId: 'intra',
    sectionId: 'intra.bloc',
    label: 'Bloc — laparotomie / damage control',
    type: 'checkbox',
    category: 'surgery',
    defaultTimeOffsetMin: 18,
    detail: { reminder: STABILITE_REMINDER },
  },
  {
    id: 'intra.bloc.arterio',
    trackId: 'intra',
    sectionId: 'intra.bloc',
    label: 'Artériographie / embolisation',
    type: 'checkbox',
    category: 'surgery',
    defaultTimeOffsetMin: 18,
  },
  {
    id: 'intra.ctb.avis',
    trackId: 'intra',
    sectionId: 'intra.ctb',
    label: 'Avis / transfert centre des brûlés',
    type: 'checkbox',
    category: 'burns',
    defaultTimeOffsetMin: 18,
    detail: {
      reminder:
        'Orientation / transfert vers un centre de traitement des brûlés (CTB) selon la surface (Wallace), la profondeur, la localisation (face, mains, périnée, plis), l’inhalation de fumées et le terrain. À articuler avec le trauma center en cas de polytraumatisme associé.',
    },
  },
]
